// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2iZOOSdLK5OXHL-JpDixZwRcg0Cdcr9g',
    appId: '1:236644575126:web:8bc4acf3fc9d8819fedfb7',
    messagingSenderId: '236644575126',
    projectId: 'flutterv2-app',
    authDomain: 'flutterv2-app.firebaseapp.com',
    storageBucket: 'flutterv2-app.firebasestorage.app',
    measurementId: 'G-RX909V8654',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb_bhQv0S3hwuFedKUJs5b_MIEsdJ5rBk',
    appId: '1:236644575126:android:72eb2b813d634a90fedfb7',
    messagingSenderId: '236644575126',
    projectId: 'flutterv2-app',
    storageBucket: 'flutterv2-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDUGT7yL5_QuB8vUV1BbWeI6dO6OO5h4U',
    appId: '1:236644575126:ios:d560bfe780fb260afedfb7',
    messagingSenderId: '236644575126',
    projectId: 'flutterv2-app',
    storageBucket: 'flutterv2-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterv290013715',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDUGT7yL5_QuB8vUV1BbWeI6dO6OO5h4U',
    appId: '1:236644575126:ios:d560bfe780fb260afedfb7',
    messagingSenderId: '236644575126',
    projectId: 'flutterv2-app',
    storageBucket: 'flutterv2-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterv290013715',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2iZOOSdLK5OXHL-JpDixZwRcg0Cdcr9g',
    appId: '1:236644575126:web:f0579b5def9b7776fedfb7',
    messagingSenderId: '236644575126',
    projectId: 'flutterv2-app',
    authDomain: 'flutterv2-app.firebaseapp.com',
    storageBucket: 'flutterv2-app.firebasestorage.app',
    measurementId: 'G-SED88NMLHG',
  );
}
